#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/under/btxcore/home \
			--quiet --gecos "under btxcore" btxcore
		chown -R btxcore /opt/under/btxcore/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
